### ISSUE TITLE
How to check for connection disconnection

### ISSUE THREAD

**Issue by abhishekranaji** [Theokalo/react-native-modbus-tcp#6]
Hi, I am trying to use this library i want to how to listen for modbus failure. like if modbus got disconnected of server got turned off. How will i get

**Comment by Theokalo** [comment]
Everytime that the response is not success you are getting a message like this "Modbus master is not inited successfully"
So, you can use an if statement to control what gonna happen after that

**Comment by abhishekranaji** [comment]
Yeah Thanks for the reply, I later on understood that it handle connection automatically
